/* GENERATED by tools/build-finance-core.js - do not edit by hand.
   Source of truth: js/calculators.js (the live calculators page).
   Regenerate:  node tools/build-finance-core.js
   Verify:      node tools/parity-test.js

   Pure, DOM-free Australian mortgage math shared by the calculators page and the
   Finance Square chatbot, so a number quoted in chat always equals the number the
   calculator on the page produces. Loads in the browser (window.FNSQFinance) and
   in Node (module.exports) alike. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.FNSQFinance = factory();
}(typeof self !== 'undefined' ? self : this, function () {
'use strict';

function money(n)  { return '$' + Math.round(n || 0).toLocaleString('en-AU'); }
function pct(n)    { return (Math.round((n || 0) * 100) / 100).toFixed(2) + '%'; }
function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }
var PER_YEAR = { weekly: 52, fortnightly: 26, monthly: 12, quarterly: 4, annually: 1 };

/* ---------- lifted verbatim from js/calculators.js ---------- */
function repayment(P, annualPct, periods, perYear) {
  var r = annualPct / 100 / perYear;
  if (r <= 0) return P / periods;
  return P * r / (1 - Math.pow(1 + r, -periods));
}

function principalFor(M, annualPct, periods, perYear) {
  var r = annualPct / 100 / perYear;
  if (r <= 0) return M * periods;
  return M * (1 - Math.pow(1 + r, -periods)) / r;
}

function termText(months) {
  if (!isFinite(months) || months < 0) return ', ';
  var y = Math.floor(months / 12), m = Math.round(months % 12);
  if (m === 12) { y++; m = 0; }
  if (!y && !m) return '0 months';
  return (y ? y + (y === 1 ? ' year' : ' years') : '') + (y && m ? ' ' : '') + (m ? m + (m === 1 ? ' month' : ' months') : '');
}

function simulate(P, annualPct, scheduledMonthly, opts) {
  opts = opts || {};
  var r = annualPct / 100 / 12;
  var bal = P, offset = opts.offsetStart || 0;
  var totalInterest = 0, m = 0, yearly = [{ month: 0, balance: Math.max(0, P - offset), interest: 0, principal: 0 }];
  var yi = 0, yp = 0;
  var ioMonths = opts.ioMonths || 0;
  var cap = 1200;

  /* The loan is discharged once the offset covers the balance - at that
     point net debt is nil and the borrower simply closes it out. Tracking
     the gross balance past that point would credit an offset with savings
     it cannot produce. */
  while ((bal - offset) > 0.01 && m < cap) {
    m++;
    if (opts.offsetMonthly) offset += opts.offsetMonthly;
    var net = Math.max(0, bal - offset);
    var interest = net * r;
    var pay = scheduledMonthly + (opts.extraMonthly || 0);
    if (m <= ioMonths) pay = interest;                       /* interest-only phase */
    if (opts.lumpAmount && m === (opts.lumpAfterMonths || 0) + 1) pay += opts.lumpAmount;
    var principal = pay - interest;
    if (principal <= 0 && m > ioMonths) { m = Infinity; break; }   /* never repays */
    if (principal > net) principal = net;
    bal -= principal;
    totalInterest += interest;
    yi += interest; yp += principal;
    if (m % 12 === 0 || (bal - offset) <= 0.01) {
      yearly.push({ month: m, balance: Math.max(0, bal - offset), interest: yi, principal: yp });
      yi = 0; yp = 0;
    }
  }
  return { months: isFinite(m) ? m : Infinity, totalInterest: totalInterest, yearly: yearly };
}

function incomeTax(gross) {
  var t;
  if (gross <= 18200) t = 0;
  else if (gross <= 45000)  t = (gross - 18200) * 0.16;
  else if (gross <= 135000) t = 4288  + (gross - 45000)  * 0.30;
  else if (gross <= 190000) t = 31288 + (gross - 135000) * 0.37;
  else                      t = 51638 + (gross - 190000) * 0.45;
  return t + (gross > 27222 ? gross * 0.02 : 0);
}

function netMonthly(gross) { return Math.max(0, gross - incomeTax(gross)) / 12; }

/* HEM-style benchmark a lender substitutes in when declared spending
   looks unrealistically low. Indicative monthly figures. */
function hemMonthly(applicants, deps) {
  return (applicants === 2 ? 3100 : 2100) + deps * 500;
}

function hemMonthly(applicants, deps) {
  return (applicants === 2 ? 3100 : 2100) + deps * 500;
}

function lmiEstimate(loan, lvr) {
  if (lvr <= 80.0001 || loan <= 0) return 0;
  var band = lvr <= 85 ? 0 : lvr <= 90 ? 1 : lvr <= 95 ? 2 : 3;
  var size = loan <= 500000 ? 0 : loan <= 750000 ? 1 : 2;
  var table = [
    [0.90, 1.30, 1.65],
    [1.90, 2.40, 2.85],
    [3.30, 3.90, 4.45],
    [4.60, 5.20, 5.80]
  ];
  return loan * table[band][size] / 100;
}

var DUTY = {
  VIC: function (v, opt) {
    var ppr = opt.use !== 'investment';
    var general;
    if (v <= 25000) general = v * 0.014;
    else if (v <= 130000)  general = 350 + (v - 25000) * 0.024;
    else if (v <= 960000)  general = 2870 + (v - 130000) * 0.06;
    else if (v <= 2000000) general = v * 0.055;
    else                   general = 110000 + (v - 2000000) * 0.065;
    var duty = general;
    if (ppr && v <= 550000) {
      if (v <= 25000) duty = v * 0.014;
      else if (v <= 130000) duty = 350 + (v - 25000) * 0.024;
      else if (v <= 440000) duty = 2870 + (v - 130000) * 0.05;
      else duty = 18370 + (v - 440000) * 0.06;
    }
    if (opt.fhb && ppr) {
      if (v <= 600000) return { duty: 0, note: 'Victorian first home buyers pay no duty on a home up to $600,000.' };
      if (v <= 750000) return { duty: duty * (v - 600000) / 150000, note: 'The Victorian first home buyer concession phases out between $600,000 and $750,000.' };
      return { duty: duty, note: 'Above $750,000 the Victorian first home buyer concession no longer applies.' };
    }
    return { duty: duty, note: ppr ? 'Victorian principal place of residence rates applied where eligible.' : 'Victorian general (non-PPR) rates applied.' };
  },

  NSW: function (v, opt) {
    var d;
    if (v <= 18000) d = Math.max(20, v * 0.0125);
    else if (v <= 38000)   d = 225 + (v - 18000) * 0.015;
    else if (v <= 103000)  d = 525 + (v - 38000) * 0.0175;
    else if (v <= 387000)  d = 1662 + (v - 103000) * 0.035;
    else if (v <= 1290000) d = 11602 + (v - 387000) * 0.045;
    else if (v <= 3870000) d = 52237 + (v - 1290000) * 0.055;
    else                   d = 194137 + (v - 3870000) * 0.07;
    if (opt.fhb && opt.use !== 'investment') {
      var cap = opt.build === 'land' ? 350000 : 800000;
      var out = opt.build === 'land' ? 450000 : 1000000;
      if (v <= cap) return { duty: 0, note: 'NSW First Home Buyers Assistance Scheme: no duty up to ' + money(cap) + '.' };
      if (v <= out) return { duty: d * (v - cap) / (out - cap), note: 'The NSW first home buyer concession phases out between ' + money(cap) + ' and ' + money(out) + '.' };
      return { duty: d, note: 'Above ' + money(out) + ' the NSW first home buyer concession no longer applies.' };
    }
    return { duty: d, note: v > 3870000 ? 'NSW premium property duty applies above the premium threshold.' : 'NSW general transfer duty scale applied.' };
  },

  QLD: function (v, opt) {
    var d;
    if (v <= 5000) d = 0;
    else if (v <= 75000)   d = (v - 5000) * 0.015;
    else if (v <= 540000)  d = 1050 + (v - 75000) * 0.035;
    else if (v <= 1000000) d = 17325 + (v - 540000) * 0.045;
    else                   d = 38025 + (v - 1000000) * 0.0575;
    if (opt.use !== 'investment') {
      var conc = Math.min(v, 350000) * (0.035 - 0.01);
      var homeDuty = Math.max(0, d - Math.max(0, conc));
      if (opt.fhb) {
        if (opt.build === 'new' || opt.build === 'land') return { duty: 0, note: 'Queensland first home buyers pay no transfer duty on a new home or vacant land build (from 1 May 2025).' };
        if (v <= 700000) return { duty: 0, note: 'Queensland first home concession: no duty on an existing first home up to $700,000.' };
        if (v <= 800000) return { duty: homeDuty * (v - 700000) / 100000, note: 'The Queensland first home concession phases out between $700,000 and $800,000.' };
        return { duty: homeDuty, note: 'Above $800,000 only the standard Queensland home concession applies.' };
      }
      return { duty: homeDuty, note: 'Queensland home concession applied to the first $350,000.' };
    }
    return { duty: d, note: 'Queensland general transfer duty scale applied (investment purchase).' };
  },

  WA: function (v) {
    var d;
    if (v <= 120000) d = v * 0.019;
    else if (v <= 150000) d = 2280 + (v - 120000) * 0.0285;
    else if (v <= 360000) d = 3135 + (v - 150000) * 0.038;
    else if (v <= 725000) d = 11115 + (v - 360000) * 0.0475;
    else d = 28453 + (v - 725000) * 0.0515;
    return { duty: d, note: 'WA residential rate of duty. The first home owner rate of duty may reduce this. Confirm with RevenueWA.' };
  },

  SA: function (v) {
    var d;
    if (v <= 12000) d = v * 0.01;
    else if (v <= 30000)  d = 120 + (v - 12000) * 0.02;
    else if (v <= 50000)  d = 480 + (v - 30000) * 0.03;
    else if (v <= 100000) d = 1080 + (v - 50000) * 0.035;
    else if (v <= 200000) d = 2830 + (v - 100000) * 0.04;
    else if (v <= 250000) d = 6830 + (v - 200000) * 0.0425;
    else if (v <= 300000) d = 8955 + (v - 250000) * 0.0475;
    else if (v <= 500000) d = 11330 + (v - 300000) * 0.05;
    else d = 21330 + (v - 500000) * 0.055;
    return { duty: d, note: 'SA conveyance duty scale. South Australia has abolished duty for eligible first home buyers on new homes. Confirm with RevenueSA.' };
  },

  TAS: function (v) {
    var d;
    if (v <= 3000) d = 50;
    else if (v <= 25000)  d = 50 + (v - 3000) * 0.0175;
    else if (v <= 75000)  d = 435 + (v - 25000) * 0.0225;
    else if (v <= 200000) d = 1560 + (v - 75000) * 0.035;
    else if (v <= 375000) d = 5935 + (v - 200000) * 0.04;
    else if (v <= 725000) d = 12935 + (v - 375000) * 0.0425;
    else d = 27810 + (v - 725000) * 0.045;
    return { duty: d, note: 'Tasmanian property transfer duty scale. First home buyer concessions may apply. Confirm with the State Revenue Office of Tasmania.' };
  },

  ACT: function (v) {
    var d;
    if (v <= 260000) d = v * 0.0049;
    else if (v <= 300000)  d = 1274 + (v - 260000) * 0.022;
    else if (v <= 500000)  d = 2154 + (v - 300000) * 0.034;
    else if (v <= 750000)  d = 8954 + (v - 500000) * 0.0432;
    else if (v <= 1000000) d = 19754 + (v - 750000) * 0.059;
    else if (v <= 1455000) d = 34504 + (v - 1000000) * 0.064;
    else d = v * 0.0454;
    return { duty: d, note: 'ACT residential conveyance duty. The ACT Home Buyer Concession Scheme can remove duty entirely under an income threshold. Confirm with the ACT Revenue Office.' };
  },

  NT: function (v) {
    var d;
    if (v < 525000) { var V = v / 1000; d = (0.06571441 * V * V) + 15 * V; }
    else if (v <= 3000000) d = v * 0.0495;
    else if (v <= 5000000) d = v * 0.0575;
    else d = v * 0.0595;
    return { duty: d, note: 'Northern Territory conveyance duty. House and land and first home owner concessions may apply. Confirm with the Territory Revenue Office.' };
  }
};

var REGISTRY = {
  VIC: { transfer: function (v) { return Math.min(3905, 110.9 + Math.ceil(v / 1000) * 2.34); }, mortgage: 120.70 },
  NSW: { transfer: function () { return 182.73; }, mortgage: 182.73 },
  QLD: { transfer: function (v) { return 231 + Math.max(0, Math.ceil((v - 180000) / 10000)) * 43; }, mortgage: 231 },
  WA:  { transfer: function () { return 220.20; }, mortgage: 210.30 },
  SA:  { transfer: function (v) { return v < 50000 ? 210 : v < 100000 ? 265 : v < 200000 ? 330 : v < 500000 ? 420 : v < 1000000 ? 560 : 700; }, mortgage: 198 },
  TAS: { transfer: function () { return 252.53; }, mortgage: 162.68 },
  ACT: { transfer: function () { return 479; }, mortgage: 178 },
  NT:  { transfer: function () { return 165; }, mortgage: 165 }
};

/* ---------- headless equivalents of the page calculators ---------- */

/* Mirrors calcBorrowing(): net income after ATO tax, HEM expense floor, credit
   limits at 3.8%/month, and the APRA 3.00pp serviceability buffer. */
function borrowingCapacity(o) {
  o = o || {};
  var applicants = o.applicants === 2 ? 2 : 1;
  var deps  = o.dependants || 0;
  var rate  = o.rate > 0 ? o.rate : 6.24;
  var years = clamp(o.years || 30, 5, 30);
  var assessRate = rate + 3.00;

  var netInc = netMonthly(o.income1 || 0) + netMonthly(o.income2 || 0) + netMonthly(o.otherIncome || 0);
  var rentMonthly = o.purpose === 'investment' ? (o.rentWeekly || 0) * 52 / 12 * 0.80 : 0;

  var hem = hemMonthly(applicants, deps);
  var usedExpenses = Math.max(o.expenses || 0, hem);
  var cardCommit = (o.cardLimits || 0) * 0.038;
  var commitments = cardCommit + (o.carLoan || 0) + (o.otherRepayments || 0);

  var surplus = netInc + rentMonthly - usedExpenses - commitments;
  var maxLoan = surplus > 0 ? principalFor(surplus, assessRate, years * 12, 12) : 0;
  maxLoan = clamp(maxLoan, 0, 8000000);

  var deposit = o.deposit || 0;
  var price = Math.max(0, (maxLoan + deposit) / 1.05);
  var costs = price * 0.05;
  var depositToLoan = Math.max(0, deposit - costs);
  var loanUsed = clamp(price - depositToLoan, 0, maxLoan);
  var lvr = price > 0 ? clamp(loanUsed / price * 100, 0, 100) : 0;

  return {
    maxLoan: maxLoan,
    low:  Math.round(maxLoan * 0.95 / 5000) * 5000,
    high: Math.round(maxLoan * 1.05 / 5000) * 5000,
    price: price,
    surplus: Math.max(0, surplus),
    assessRate: assessRate,
    rate: rate,
    years: years,
    monthlyRepayment: maxLoan > 0 ? repayment(maxLoan, rate, years * 12, 12) : 0,
    lvr: lvr,
    lmi: lmiEstimate(loanUsed, lvr),
    benchmarkExpenses: usedExpenses,
    hemApplied: usedExpenses > (o.expenses || 0),
    commitments: commitments,
    cardCommitment: cardCommit
  };
}

/* Mirrors calcDuty(): duty + transfer + mortgage registration, and the LMI and
   cash-needed figures the upfront-costs panel shows. */
function stampDuty(o) {
  o = o || {};
  var state = String(o.state || 'VIC').toUpperCase();
  if (!DUTY[state]) return null;
  var v = o.value || 0;
  var use = o.use === 'investment' ? 'investment' : 'home';
  var fhb = use === 'investment' ? false : !!o.firstHomeBuyer;

  var res = DUTY[state](v, { use: use, fhb: fhb, build: o.build || 'existing' });
  var duty = Math.max(0, res.duty);
  var reg = REGISTRY[state];
  var transferFee = reg.transfer(v);
  var mortgageFee = reg.mortgage;

  var deposit = o.deposit || 0;
  var loan = Math.max(0, v - deposit);
  var lvr = v > 0 ? loan / v * 100 : 0;
  var lmi = lmiEstimate(loan, lvr);
  var legals = o.legals == null ? 2000 : o.legals;
  var govt = duty + transferFee + mortgageFee;

  return {
    state: state, value: v, duty: duty, note: res.note,
    effectiveRate: v > 0 ? duty / v * 100 : 0,
    transferFee: transferFee, mortgageFee: mortgageFee, government: govt,
    lmi: lmi, legals: legals, upfront: govt + lmi + legals,
    cashNeeded: deposit + govt + legals,
    loan: loan, lvr: lvr, firstHomeBuyer: fhb
  };
}

/* Repayments for a plain loan, at any repayment frequency. */
function loanRepayments(o) {
  o = o || {};
  var P = o.amount || 0;
  var rate = o.rate > 0 ? o.rate : 6.24;
  var years = o.years || 30;
  var perYear = PER_YEAR[o.frequency] || 12;
  var periods = Math.round(years * perYear);
  var pay = P > 0 ? repayment(P, rate, periods, perYear) : 0;
  var monthly = P > 0 ? repayment(P, rate, years * 12, 12) : 0;
  var totalPaid = pay * periods;
  return {
    amount: P, rate: rate, years: years, frequency: o.frequency || 'monthly',
    perYear: perYear, payment: pay, monthly: monthly,
    totalPaid: totalPaid, totalInterest: Math.max(0, totalPaid - P),
    interestOnly: P * rate / 100 / 12
  };
}

/* What extra repayments or a lump sum do to the term and the interest bill. */
function extraRepayments(o) {
  o = o || {};
  var P = o.amount || 0;
  var rate = o.rate > 0 ? o.rate : 6.24;
  var years = o.years || 30;
  var base = repayment(P, rate, years * 12, 12);
  var a = simulate(P, rate, base, {});
  var b = simulate(P, rate, base, {
    extraMonthly: o.extraMonthly || 0,
    lumpAmount: o.lumpAmount || 0,
    lumpAfterMonths: o.lumpAfterMonths || 0
  });
  return {
    baseMonthly: base,
    baseMonths: a.months, baseInterest: a.totalInterest,
    newMonths: b.months, newInterest: b.totalInterest,
    monthsSaved: a.months - b.months,
    interestSaved: a.totalInterest - b.totalInterest
  };
}

return {
  money: money, pct: pct, termText: termText,
  repayment: repayment, principalFor: principalFor, simulate: simulate,
  incomeTax: incomeTax, netMonthly: netMonthly, hemMonthly: hemMonthly,
  lmiEstimate: lmiEstimate,
  DUTY: DUTY, REGISTRY: REGISTRY, STATES: Object.keys(DUTY),
  borrowingCapacity: borrowingCapacity,
  stampDuty: stampDuty,
  loanRepayments: loanRepayments,
  extraRepayments: extraRepayments
};
}));
